### ISSUE TITLE
Differences with humble-router. 

### ISSUE THREAD

**Issue by pratapsu** [marwan-at-work/vecty-router#4]
Marwan: 

Could you help me understand the differences between your package and the humble router? 
You cite them in your README.md, but you don't go into any detail, as to why one will use the 
vecty-router versus the hunble one. 

Thanks!

Pratap

**Comment by marwan-at-work** [comment]
@pratapsu humble-router is framework agnostic while vecty-router is specific to vecty. I also wanted the API of vecty-router to be similar to react-router (v4) in that you can declare a route anywhere in your component and they don't all have to be at the top level.

**Comment by pratapsu** [comment]
Is there a "navigate" equivalent in vecty-router? If not, how may I effect
a link traversal when I say, click a button?

Pratap

**Comment by marwan-at-work** [comment]
@pratapsu yes, see `router.Redirect`
