### ISSUE TITLE
cannot parse import comment

### ISSUE THREAD

**Issue by xoviat** [marwan-at-work/vecty-router#8]
When I attempt to build, I receive the following error. 

```
C:\Go\bin\go build -o main.wasm
components\body.go:7:2: go\src\marwan.io\vecty-router\doc.go:1: cannot parse import comment

```
If I remove doc.go, then the project builds. I am not sure whether you would be amenable to this or not.

**Comment by marwan-at-work** [comment]
@xoviat thank you for reporting this, I think I'm missing the quotes around the import statement in `doc.go` -- I pushed a patch so please let me know if this fixes your issue. 

Just FYI, vecty only supports gopherjs and not wasm and so vecty-router won't work with wasm until vecty does.

**Comment by xoviat** [comment]
I've submitted #7 to add wasm capability to vecty-router (the patch is compatible with both wasm and gopherjs).  Vecty does not yet officially support wasm, but there is gopherjs/vecty#232 that works well enough that I can use it with my local development application.

**Comment by xoviat** [comment]
Oh, and the patch works.

**Comment by marwan-at-work** [comment]
@xoviat got it. Will close the issue then. Thanks for the contribution :)
